### ISSUE TITLE
Don't use lateinit

### ISSUE THREAD

**Issue by SPC-code** [abdiganieva/kotlin-client#2]
https://github.com/abdiganieva/kotlin-client/blob/851a86bf25d39466343ea2156d1ddfe7246ba874/src/main/kotlin/Client.kt#L15

Lateinit is considered bad practice everywhere outside interop cases. Please revise architecture to avoid using lateinit.

**Comment by abdiganieva** [comment]
I believe simply replacing everything with nullable types is not the best solution but I can't come up with something more fitting at the moment

**Comment by abdiganieva** [comment]
I wonder if this fix only made thing worse

**Comment by abdiganieva** [comment]
I've decided to exclude null types
